### ISSUE TITLE
Week11 mf4024

### ISSUE THREAD

**Issue by mf4024** [ac7407/comp-lab-class#11]
Good Works! Most parts seem right. However, it seems like you are missing some smiles strings. Here is your supposed smiles.csv:

smiles
C=C
C=O
C#N
CCO
CCC(=O)O
CN=C=O
c1cc(O)ccc1 #Missing
c1ccncc1 #Missing
c1cc(C(O)=O)ccc1 #Missing
c1ccc2cnccc2c1 #Missing

**Comment by ac7407** [comment]
Added remaining aromatic compounds.
