### ISSUE TITLE
Week 8 Feedback

### ISSUE THREAD

**Issue by ns3539** [ac7407/comp-lab-class#3]
Setup: Missing the /melt directory and associated files from running in.melt

Trajectories:
The trajectories folder should contain .dcd files for each run as well as .log files. The .log files are present and clearly labeled in the /Data directory; these can be copied over. The .dcd files are missing/not present

Figures:
There is no /Figures directory. This directory should contain 2 images for 2d WCA, one for which crystallization was observed and one noncrystalline, clearly labeled. Similarly 2 images for 3d WCA. There are snapshots for all densities within your /Trajectories directory, so you can find the point at which crystallization occurs and copy over the images for that density and the one below it in a new /Figures directory
mpg movie from Setup is missing. This should also be part of /Figures directory

**Comment by ac7407** [comment]
Revisions have been made.
