### ISSUE TITLE
Week 11 Feedback

### ISSUE THREAD

**Issue by ns3539** [ac7407/comp-lab-class#4]
Task 1 (test_pskit.ipynb): Good! Tutorial is complete and includes clear comments to label each task

Task 2 (charge_comparsion_pyridine.ipynb): Great! All parts complete and the bonus charge labeling was done successfully

Task 3 (energy_table.ipynb): Missing last 5 smiles strings in .csv file. There should be 10 total. Otherwise everything was done correctly for the smiles strings that are present in the file

**Comment by ac7407** [comment]
Added remaining aromatic compounds.
