### ISSUE TITLE
Week 8 comment mf4024

### ISSUE THREAD

**Issue by mf4024** [ac7407/comp-lab-class#9]
Good Work, I think you have most of the files, but there are some minor issues.

1) Your Trajectories folder should contain log files and lammpstrj files

2). You only need two pictures from the 2d system; crystallized and non-crystallized pictures. The same applies to the 3d system.

**Comment by ac7407** [comment]
Just uploaded .log files and .lammpstrj files for both the 2d and 3d system.

**Comment by ac7407** [comment]
Second issue has also been resolved.
